### ISSUE TITLE
Bug in text generation code

### ISSUE THREAD

**Issue by mkroutikov** [mkroutikov/tf-lstm-char-cnn#10]
Discovered by @derluke. RNN state is not re-used. This should explain somewhat poor-looking generated text sample in README.md

@derluke, please create pull request with your fix.

**Comment by derluke** [comment]
Hi @mkroutikov, 
there is a pull request open.

Cheers

**Comment by mkroutikov** [comment]
Thanks @derluke ! Missed the notification, sorry.

Closing this issue as resolved.

Also, check few latest updates to the repo:
* Fixed `evaluate.py` and `generate.py` to check model existence (following breaking changes in TF 0.12)
* README.md shows the latest "dreamed" text
* pre-trained model can be downloaded from link in the README.md
* Contributors section in the README.md updated
