### ISSUE TITLE
generate.py - both tensors must match - error

### ISSUE THREAD

**Issue by GenTxt** [mkroutikov/tf-lstm-char-cnn#11]
Hello:

Thanks for posting this updated version. I have tested your previous versions that ran on tensorflow 11 or earlier and all ran without errors.

I can generate models with the latest tf 12 version but when I run generate.py (latest version posted 7 hours ago) using your training data archive I encounter this error. Occurs with python 2 or 3, ubuntu 16-64 bit, Cuda 8, tf 12.1

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [81,15] rhs shape= [51,15]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@Model/Embedding/char_embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Model/Embedding/char_embedding, save/RestoreV2/_57)]]

Any suggestions on how to fix?

Thanks

**Comment by mkroutikov** [comment]
make sure you run generate with the same graph (`rnn_size` and other parameters).

rule of thumb is: if you trained with a set of params, use the same settings when running prediction (and generation).
