### ISSUE TITLE
A wrong comment in tdnn about the dim of conv

### ISSUE THREAD

**Issue by doxawang** [mkroutikov/tf-lstm-char-cnn#18]
the comment in line 95 says 

`# [batch_size x max_word_length x embed_size x kernel_feature_size]`

, which I think actually should be

`[batch_size x 1 x reduced_length x kernel_feature_size]`

That confused me a lot as I'm a beginner to TF.

And you also seem to omit all the `num_unroll_steps` in the comments of this part.

**Comment by mkroutikov** [comment]
yes, comments are obsolete... some were leftovers from the parent project.

sorry if that caused you a confusion.

could you make a PR that fixes the comments?

**Comment by mkroutikov** [comment]
Fixed
