### ISSUE TITLE
Shape (35,20,10000) must have rank 2

### ISSUE THREAD

**Issue by guanghuixu** [mkroutikov/tf-lstm-char-cnn#4]
Thank you for sharing your code. But I have some problem in training with your code? It has the error:Shape (35,20,10000) must have rank 2. How can I do anything? I'm a university student, thank you.

**Comment by mkroutikov** [comment]
Nicole, what is the command line? and could you please post the trace stack here?

Thanks!

**Comment by claravania** [comment]
Hi, many thanks for your implementation.

I also found the same issue until I realised that I used different TF v0.9. When I changed to v0.10, it works for me, hope that helps!
